<?

namespace backend\modules\swp\controllers;
use backend\modules\swp\controllers\common\CRUDController;

use backend\modules\swp\models\Field;
use common\models\swp\search\Field as FieldSearch;
use yii\web\NotFoundHttpException;

class FieldController extends CRUDController
{
    public function init()
    {
        $this->mainClass = Field::className();
        $this->searchClass = FieldSearch::className();
        $this->parentController = '/swp/group';
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @throws NotFoundHttpException
     */
    public function actionIndex($group = 0)
    {
        throw new NotFoundHttpException();
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveClose($model)
    {
        /** @var Field $model */
        if (!$model->group_id) {
            return $this->redirect([$this->parentController, 'tab' => 'fields']);
        }
        return $this->redirect([$this->parentController . '/update', 'id' => $model->group->id, 'tab' => 'sub-field']);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCreate($model)
    {
        $this->redirect(['create', 'group' => $model->group_id ? $model->group->id : null]);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCopy($model)
    {
        $this->redirect(['create', 'group' => $model->group_id ? $model->group->id : null, 'copy' => $model->id]);
    }
}
