<?php

namespace backend\modules\swp\controllers;
use backend\modules\swp\controllers\common\CRUDController;
use backend\modules\swp\models\Group;
use common\models\swp\search\Group as GroupSearch;

/**
 * Default controller for the `swp` module
 */
class GroupController extends CRUDController
{
    public function init()
    {
        $this->mainClass = Group::className();
        $this->searchClass = GroupSearch::className();
        $this->parentController = '/swp/group';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex($group = 0)
    {
        return parent::actionIndex($group); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveClose($model)
    {
        if ($model->group_id) {
            return $this->redirect([$this->parentController . '/update', 'id' => $model->group->id, 'tab' => 'sub-group']);
        }
        return parent::submitSaveClose($model);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCreate($model)
    {
        $this->redirect(['create', 'group' => $model->group->id]);
    }

    /**
     * {@inheritdoc}
     */
    protected function submitSaveCopy($model)
    {
        $this->redirect(['create', 'group' => $model->group->id, 'copy' => $model->id]);
    }
}
