<?php

namespace backend\widgets;


use Yii;
use yii\base\Widget;
use yii\helpers\Html;

class FormWidget extends Widget
{
    public $copyable;
    public $creatable;
    public $onlySave = false;
    public $close = null;
    public function run()
    {
        $this->view->registerJs($this->javaScript(), \yii\web\View::POS_READY);
        echo '<div class="form-group multiple-buttons">';
        echo Html::submitButton('Сохранить', ['name' => 'save', 'class' => 'btn btn-success']);
        if (!$this->onlySave) {
            echo Html::submitButton('Сохранить и закрыть', ['name' => 'save-close', 'class' => 'btn btn-primary']);
            if ($this->creatable) {
                echo Html::submitButton('Сохранить и создать', ['name' => 'save-create', 'class' => 'btn btn-primary']);
            }
            if ($this->copyable)
                echo Html::submitButton('Сохранить и копировать', ['name' => 'save-copy', 'class' => 'btn btn-primary']);
            echo Html::a('<i class="fa fa-close"></i>', $this->close ? $this->close : ['index'], [
                'class' => 'btn btn-danger',
                'title' => 'Выход',
            ]);
        }
        echo '</div>';
        $tab =  Yii::$app->getRequest()->getQueryParams()['tab'];
        echo Html::hiddenInput('tab', $tab ? $tab : '');
        parent::run(); // TODO: Change the autogenerated stub
    }

    private function javaScript()
    {
        $script = <<<JS
        function addLocationTag(target) {
        var noHashURL;
            if (window.location.href.search(/.*.&tab=.*/) < 0) {
                noHashURL = window.location.href.replace(/$/, '&tab='+target);
            } else {
                noHashURL = window.location.href.replace(/&tab=.*$/, '&tab='+target);
            }
        window.history.replaceState('', document.title, noHashURL)
    }

    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        var target = $(e.target).attr("href").slice(1);
        $('input[name="tab"]').val(target);
        addLocationTag(target);
    });
JS;
        return $script;
    }
}
